version: '3.9'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgis_docker_postgres
    # restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 6432:5432

  adminer:
    image: adminer
    container_name: postgis_docker_adminer
    # restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
